"""Dataset access with schema validation and an integrity manifest.

The bundled datasets are synthetic (generated by :mod:`plotlyvizpro.datasets`
from a fixed seed). :func:`load` reads one by name, parses dates, checks the
expected columns, and, when a manifest is present, verifies the file's
SHA-256 so a figure's provenance can be traced to exact bytes.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd

from plotlyvizpro._typing import StrPath
from plotlyvizpro.provenance import sha256_of_file

MANIFEST_NAME = "manifest.json"


@dataclass(frozen=True)
class DatasetSpec:
    """Expected shape of a bundled dataset."""

    filename: str
    columns: tuple[str, ...]
    date_columns: tuple[str, ...] = ()
    description: str = ""
    sort_by: tuple[str, ...] = field(default_factory=tuple)


SPECS: dict[str, DatasetSpec] = {
    "superstore": DatasetSpec(
        "superstore.csv",
        ("OrderID", "OrderDate", "Category", "SubCategory", "Region", "Sales", "Profit"),
        ("OrderDate",),
        "1000 synthetic retail orders across categories and regions.",
        ("OrderDate",),
    ),
    "covid": DatasetSpec(
        "covid_data.csv",
        ("Country", "Date", "Cases", "Deaths"),
        ("Date",),
        "Daily cumulative cases/deaths for five countries over one year (random walk).",
        ("Country", "Date"),
    ),
    "stocks": DatasetSpec(
        "stock_data.csv",
        ("Company", "Date", "Open", "Close", "High", "Low", "Volume"),
        ("Date",),
        "180 days of OHLCV for three synthetic tickers.",
        ("Company", "Date"),
    ),
    "world_population": DatasetSpec(
        "world_population.csv",
        ("Country", "Population", "GDP_per_capita", "Life_Expectancy", "Continent"),
        (),
        "Country-level indicators (synthetic).",
    ),
    "customers": DatasetSpec(
        "customer_segments.csv",
        ("CustomerID", "Gender", "Age", "Income", "Segment", "Region"),
        (),
        "500 synthetic customers with demographic attributes.",
    ),
    "product_launch": DatasetSpec(
        "product_launch.csv",
        ("Product", "Stage", "Week", "Sales", "MarketingSpend"),
        (),
        "Lifecycle-stage sales and marketing spend for three products.",
    ),
    "map_points": DatasetSpec(
        "map_data.csv",
        ("City", "Latitude", "Longitude", "Score"),
        (),
        "100 synthetic city coordinates with a score.",
    ),
    "animated_sales": DatasetSpec(
        "animated_sales.csv",
        ("Month", "Category", "Sales"),
        (),
        "Monthly category sales for one year, used for animation demos.",
        ("Month", "Category"),
    ),
}


def datasets_dir() -> Path:
    """Directory containing the bundled CSV files (``<project>/datasets``)."""
    return Path(__file__).resolve().parent.parent / "datasets"


def list_datasets() -> list[str]:
    """Names accepted by :func:`load`."""
    return sorted(SPECS)


class SchemaError(ValueError):
    """Raised when a dataset file does not match its declared schema."""


class IntegrityError(ValueError):
    """Raised when a dataset's SHA-256 does not match the manifest."""


def load(name: str, *, directory: StrPath | None = None, verify: bool = True) -> pd.DataFrame:
    """Load a bundled dataset by name.

    Parameters
    ----------
    name:
        A key of :data:`SPECS` (see :func:`list_datasets`).
    directory:
        Override the datasets directory (e.g. for tests).
    verify:
        Check the file's SHA-256 against ``manifest.json`` when that file exists.

    Raises
    ------
    KeyError
        Unknown dataset name.
    FileNotFoundError
        The CSV is missing (run ``plotlyvizpro generate-data``).
    SchemaError
        Required columns are missing.
    IntegrityError
        The file's digest does not match the manifest.
    """
    if name not in SPECS:
        raise KeyError(f"Unknown dataset {name!r}. Available: {list_datasets()}")
    spec = SPECS[name]
    base = Path(directory) if directory is not None else datasets_dir()
    path = base / spec.filename
    if not path.exists():
        raise FileNotFoundError(f"{path} not found; run `plotlyvizpro generate-data` to create the datasets")
    if verify:
        manifest_path = base / MANIFEST_NAME
        if manifest_path.exists():
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            expected = manifest.get("files", {}).get(spec.filename, {}).get("sha256")
            actual = sha256_of_file(path)
            if expected and expected != actual:
                raise IntegrityError(f"{spec.filename}: sha256 {actual[:12]}… does not match manifest {expected[:12]}…")
    df = pd.read_csv(path, parse_dates=list(spec.date_columns))
    missing = [c for c in spec.columns if c not in df.columns]
    if missing:
        raise SchemaError(f"{spec.filename} is missing columns {missing}")
    if spec.sort_by:
        df = df.sort_values(list(spec.sort_by), kind="stable").reset_index(drop=True)
    return df


def write_manifest(
    directory: StrPath | None = None, *, seed: int | None = None, extra: dict[str, object] | None = None
) -> Path:
    """Write ``manifest.json`` with the SHA-256, size and row count of each dataset."""
    base = Path(directory) if directory is not None else datasets_dir()
    files: dict[str, dict[str, object]] = {}
    for spec in SPECS.values():
        path = base / spec.filename
        if not path.exists():
            continue
        with open(path, "rb") as fh:
            rows = sum(1 for _ in fh) - 1
        files[spec.filename] = {
            "sha256": sha256_of_file(path),
            "bytes": path.stat().st_size,
            "rows": rows,
            "columns": list(spec.columns),
            "description": spec.description,
        }
    payload: dict[str, object] = {"seed": seed, "files": files, **(extra or {})}
    out = base / MANIFEST_NAME
    out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return out


def verify_manifest(directory: StrPath | None = None) -> dict[str, bool]:
    """Return ``filename -> matches`` for every entry in the manifest."""
    base = Path(directory) if directory is not None else datasets_dir()
    manifest = json.loads((base / MANIFEST_NAME).read_text(encoding="utf-8"))
    return {
        fname: (base / fname).exists() and sha256_of_file(base / fname) == entry["sha256"]
        for fname, entry in manifest["files"].items()
    }
